export default {
  // App
  app: {
    name: 'VitaInes',
    tagline: 'Know Your Numbers, Own Your Health',
    disclaimer: 'This app does not replace professional medical advice. Always consult your doctor.',
  },

  // Language toggle
  language: {
    toggle: 'Español',
    english: 'English',
    spanish: 'Español',
  },

  // Navigation
  nav: {
    home: 'Home',
    readings: 'Readings',
    medications: 'Medications',
    history: 'History',
    insights: 'Insights',
    profile: 'Profile',
  },

  // Onboarding
  onboarding: {
    welcome: 'Welcome to VitaInes',
    welcome_subtitle: 'Your personal blood pressure companion',
    get_started: 'Get Started',
    next: 'Next',
    back: 'Back',
    finish: 'Finish Setup',
    skip: 'Skip for now',
    step_of: 'Step {{current}} of {{total}}',

    step1_title: 'Measurement Schedule',
    step1_subtitle: 'How many times per day would you like to measure your blood pressure?',
    once_daily: 'Once daily',
    twice_daily: 'Twice daily',
    three_times: 'Three times daily',

    step2_title: 'Reminder Times',
    step2_subtitle: 'When would you like to be reminded?',
    morning: 'Morning',
    afternoon: 'Afternoon',
    evening: 'Evening',
    morning_range: '7 AM – 9 AM',
    afternoon_range: '1 PM – 3 PM',
    evening_range: '7 PM – 9 PM',
    select_times: 'Select your preferred reminder windows',

    step3_title: 'Your Medications',
    step3_subtitle: 'Add your blood pressure medications (optional)',
    add_medication: 'Add Medication',
    skip_medication: 'I\'ll add medications later',
    feature_track: 'Track your blood pressure readings',
    feature_history: 'View trends and history charts',
    feature_insights: 'Get personalized AI health insights',
    feature_meds: 'Manage your medications',
    welcome_title: 'Welcome to VitaInes',
    welcome_subtitle: 'Your personal blood pressure health companion',
    ready_label: 'Ready to get started?',
  },

  // Dashboard / Home
  home: {
    good_morning: 'Good morning',
    good_afternoon: 'Good afternoon',
    good_evening: 'Good evening',
    last_reading: 'Last Reading',
    no_readings: 'No readings yet',
    add_reading: 'Add Reading',
    quick_log: 'Quick Log',
    todays_reminder: 'Today\'s Reminder',
    take_reading_now: 'Take a reading now',
    readings_today: '{{count}} reading(s) today',
    streak: '{{count}} day streak',
    ai_insight: 'Health Insight',
    view_all: 'View all',
    medications_due: 'Medications Due',
    all_caught_up: 'All caught up!',
  },

  // Blood pressure reading
  reading: {
    title: 'Log Blood Pressure',
    systolic: 'Systolic',
    diastolic: 'Diastolic',
    pulse: 'Pulse',
    systolic_hint: 'Top number',
    diastolic_hint: 'Bottom number',
    pulse_hint: 'Beats per minute',
    notes: 'Notes (optional)',
    notes_placeholder: 'How are you feeling?',
    save: 'Save Reading',
    saving: 'Saving...',
    saved: 'Reading saved!',
    cancel: 'Cancel',
    date_time: 'Date & Time',
    now: 'Now',

    // Status labels
    normal: 'Normal',
    elevated: 'Elevated',
    high: 'High',
    crisis: 'Call Doctor',

    // Status descriptions
    normal_desc: 'Your blood pressure is in a healthy range.',
    elevated_desc: 'Your blood pressure is slightly elevated.',
    high_desc: 'Your blood pressure is high. Monitor closely.',
    crisis_desc: 'Your blood pressure is very high. Contact your doctor immediately.',

    // Validation
    enter_systolic: 'Please enter systolic pressure',
    enter_diastolic: 'Please enter diastolic pressure',
    invalid_systolic: 'Systolic should be between 60 and 250',
    invalid_diastolic: 'Diastolic should be between 40 and 150',
    invalid_pulse: 'Pulse should be between 30 and 200',
    returning: 'Returning to home…',
  },

  // History & Charts
  history: {
    title: 'History',
    filter_day: 'Day',
    filter_week: 'Week',
    filter_month: 'Month',
    filter_two_weeks: '2 Weeks',
    filter_thirty_days: '30 Days',
    filter_custom: 'Custom',
    filter_today: 'Today',
    filter_7_days: '7 Days',
    filter_30_days: '30 Days',
    filter_90_days: '90 Days',
    filter_6_months: '6 Mo',
    filter_1_year: '1 Year',
    no_data: 'No readings in this period',
    average: 'Average',
    highest: 'Highest',
    lowest: 'Lowest',
    readings_count: '{{count}} readings',
    systolic_label: 'Systolic',
    diastolic_label: 'Diastolic',
    threshold_line: 'Normal limit',
    date_range: '{{start}} – {{end}}',
    export: 'Export',
    export_pdf: 'Export PDF',
    exporting_pdf: 'Generating…',
    bp_trend: 'Blood Pressure Trend',
    bp_subtitle: 'Red = Systolic · Blue = Diastolic · Dashes = Thresholds',
    pulse_trend: 'Pulse Trend',
    all_readings: 'All Readings',
    show_more: 'Show all {{count}} readings',
    custom_start: 'From',
    custom_end: 'To',
    avg_pulse: 'Avg Pulse',
    select_range: 'Select Date Range',
    try_different: 'Try a different time range',
    latest_reading: 'Latest Reading',
    bp_warning: 'Readings above 140 mmHg may require medical attention',
    pulse_warning: 'Readings above 100 bpm may indicate elevated heart rate',
    legend_normal_line: 'Normal (120)',
    legend_high_line: 'High (140)',
    legend_pulse_limit: 'Limit (100 bpm)',
  },

  // Medications
  medications: {
    title: 'Medications',
    add: 'Add Medication',
    edit: 'Edit',
    delete: 'Delete',
    pause: 'Pause',
    resume: 'Resume',
    name: 'Medication Name',
    search_placeholder: 'Search medications...',
    dosage: 'Dosage',
    frequency: 'Frequency',
    once_daily: 'Once daily',
    twice_daily: 'Twice daily',
    three_times_daily: 'Three times daily',
    four_times_daily: 'Four times daily',
    as_needed: 'As needed',
    doctor_notes: 'Doctor\'s Notes',
    doctor_notes_placeholder: 'Special instructions from your doctor...',
    save: 'Save Medication',
    delete_confirm: 'Are you sure you want to delete this medication?',
    delete_yes: 'Yes, Delete',
    delete_no: 'Cancel',
    paused_label: 'Paused',
    active_label: 'Active',
    no_medications: 'No medications added yet',
    add_first: 'Add your first medication',
    reminder_set: 'Reminder set',
    category: 'Category',
  },

  // AI Recommendations
  ai: {
    title: 'Health Insights',
    powered_by: 'AI Health Assistant',
    loading: 'Analyzing your readings...',
    no_data: 'Log a reading to receive personalized insights.',
    disclaimer: 'These suggestions are for informational purposes only. Consult your doctor before making changes.',
    refresh: 'Get New Insight',
    categories: {
      food: 'Nutrition',
      exercise: 'Activity',
      hydration: 'Hydration',
      sleep: 'Sleep',
      stress: 'Stress',
      general: 'General',
      warning: 'Important',
    },
  },

  // Notifications
  notifications: {
    bp_reminder_title: 'Time to check your blood pressure',
    bp_reminder_body: 'Take a moment to log your reading.',
    medication_reminder_title: 'Medication reminder',
    medication_reminder_body: 'Time to take your {{medication}}.',
    elevated_warning_title: 'Elevated blood pressure detected',
    elevated_warning_body: 'Your last reading was {{systolic}}/{{diastolic}}. Monitor closely.',
    high_warning_title: 'High blood pressure alert',
    high_warning_body: 'Your reading of {{systolic}}/{{diastolic}} is high. Consider contacting your doctor.',
    crisis_warning_title: 'Urgent: Very high blood pressure',
    crisis_warning_body: 'Reading {{systolic}}/{{diastolic}} requires immediate medical attention.',
    missed_reading_title: 'Did you forget your reading?',
    missed_reading_body: 'You haven\'t logged a reading today. Stay on track!',
  },

  // Profile
  profile: {
    title: 'Profile',
    name: 'Name',
    age: 'Age',
    doctor_name: 'Doctor\'s Name',
    doctor_phone: 'Doctor\'s Phone',
    emergency_contact: 'Emergency Contact',
    target_systolic: 'Target Systolic',
    target_diastolic: 'Target Diastolic',
    save: 'Save Profile',
    notifications: 'Notifications',
    reminders: 'Reminders',
    language: 'Language',
    data_export: 'Export My Data',
    sign_out: 'Sign Out',
    sign_out_confirm: 'Are you sure you want to sign out?',
    data_retention: 'Data is automatically deleted after 2 years.',
    version: 'Version',
  },

  // Auth
  auth: {
    sign_in: 'Sign In',
    sign_up: 'Create Account',
    email: 'Email Address',
    password: 'Password',
    confirm_password: 'Confirm Password',
    forgot_password: 'Forgot Password?',
    reset_password: 'Reset Password',
    no_account: 'Don\'t have an account?',
    have_account: 'Already have an account?',
    create_account: 'Create Account',
    or: 'or',
    continue_with_google: 'Continue with Google',
    terms: 'By continuing, you agree to our Terms of Service and Privacy Policy.',
    error_title: 'Sign In Error',
    error_invalid_email: 'Please enter a valid email address.',
    error_weak_password: 'Password must be at least 6 characters.',
    error_passwords_dont_match: 'Passwords do not match.',
    error_generic: 'Something went wrong. Please try again.',
    error_invalid_credentials: 'Incorrect email or password.',
    error_email_in_use: 'An account with this email already exists.',
    error_too_many_requests: 'Too many attempts. Please wait a moment and try again.',
    error_network: 'No internet connection. Please check your network and try again.',
    error_user_disabled: 'This account has been disabled. Please contact support.',
    error_operation_not_allowed: 'Email sign-in is not enabled. Please contact support.',
    error_google_failed: 'Google sign-in failed. Please try again.',
    error_google_not_configured: 'Google Sign-In is not yet configured for this build. Please use email/password sign-in.',
    error_name_required: 'Please enter your name.',
    error_weak_password_strong: 'Password must be at least 8 characters and include uppercase, lowercase, and a number.',
    error_reset_no_user: 'No account found with this email address.',
    signup_error_title: 'Sign Up Error',

    // Password strength requirements
    password_req_length: 'At least 8 characters',
    password_req_upper: 'One uppercase letter (A–Z)',
    password_req_lower: 'One lowercase letter (a–z)',
    password_req_number: 'One number (0–9)',

    // Forgot password
    forgot_password_title: 'Reset Password',
    forgot_password_subtitle: 'Enter your email and we\'ll send you a reset link.',
    send_reset_link: 'Send Reset Link',
    reset_sent_title: 'Email Sent!',
    reset_sent_message: 'Check your inbox for the password reset link. It may take a minute to arrive.',
    reset_error_title: 'Reset Failed',
    back_to_sign_in: 'Back to Sign In',

    // Sign up success
    signup_success_title: 'Account Created!',
    signup_success_subtitle: 'Welcome to VitaInes',
    signup_success_email_label: 'A confirmation email has been sent to:',
    signup_success_note: 'Please check your inbox and follow the link to verify your email address.',
    go_to_sign_in: 'Go to Sign In',
    signup_auto_redirect: 'You\'ll be redirected to sign in automatically in a few seconds.',
  },

  // Common
  common: {
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    back: 'Back',
    close: 'Close',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    loading: 'Loading...',
    error: 'Something went wrong',
    retry: 'Try again',
    no_internet: 'No internet connection',
    done: 'Done',
    today: 'Today',
    yesterday: 'Yesterday',
    mmhg: 'mmHg',
    bpm: 'bpm',
    morning: 'Morning',
    afternoon: 'Afternoon',
    evening: 'Evening',
  },
};
