export default {
  // App
  app: {
    name: 'VitaInes',
    tagline: 'Tu Compañero de Salud',
    disclaimer: 'Esta aplicación no reemplaza el consejo médico profesional. Siempre consulta a tu médico.',
  },

  // Language toggle
  language: {
    toggle: 'English',
    english: 'English',
    spanish: 'Español',
  },

  // Navigation
  nav: {
    home: 'Inicio',
    readings: 'Lecturas',
    medications: 'Medicamentos',
    history: 'Historial',
    profile: 'Perfil',
  },

  // Onboarding
  onboarding: {
    welcome: 'Bienvenido a VitaInes',
    welcome_subtitle: 'Tu compañero personal de presión arterial',
    get_started: 'Comenzar',
    next: 'Siguiente',
    back: 'Atrás',
    finish: 'Finalizar Configuración',
    skip: 'Omitir por ahora',
    step_of: 'Paso {{current}} de {{total}}',

    step1_title: 'Horario de Medición',
    step1_subtitle: '¿Cuántas veces al día deseas medir tu presión arterial?',
    once_daily: 'Una vez al día',
    twice_daily: 'Dos veces al día',
    three_times: 'Tres veces al día',

    step2_title: 'Horarios de Recordatorio',
    step2_subtitle: '¿Cuándo deseas recibir recordatorios?',
    morning: 'Mañana',
    afternoon: 'Tarde',
    evening: 'Noche',
    morning_range: '7 AM – 9 AM',
    afternoon_range: '1 PM – 3 PM',
    evening_range: '7 PM – 9 PM',
    select_times: 'Selecciona tus ventanas de recordatorio preferidas',

    step3_title: 'Tus Medicamentos',
    step3_subtitle: 'Agrega tus medicamentos para la presión arterial (opcional)',
    add_medication: 'Agregar Medicamento',
    skip_medication: 'Agregaré medicamentos después',
  },

  // Dashboard / Home
  home: {
    good_morning: 'Buenos días',
    good_afternoon: 'Buenas tardes',
    good_evening: 'Buenas noches',
    last_reading: 'Última Lectura',
    no_readings: 'Sin lecturas aún',
    add_reading: 'Agregar Lectura',
    quick_log: 'Registro Rápido',
    todays_reminder: 'Recordatorio de Hoy',
    take_reading_now: 'Toma una lectura ahora',
    readings_today: '{{count}} lectura(s) hoy',
    streak: '{{count}} días seguidos',
    ai_insight: 'Consejo de Salud',
    view_all: 'Ver todo',
    medications_due: 'Medicamentos Pendientes',
    all_caught_up: '¡Todo al día!',
  },

  // Blood pressure reading
  reading: {
    title: 'Registrar Presión Arterial',
    systolic: 'Sistólica',
    diastolic: 'Diastólica',
    pulse: 'Pulso',
    systolic_hint: 'Número superior',
    diastolic_hint: 'Número inferior',
    pulse_hint: 'Latidos por minuto',
    notes: 'Notas (opcional)',
    notes_placeholder: '¿Cómo te sientes?',
    save: 'Guardar Lectura',
    saving: 'Guardando...',
    saved: '¡Lectura guardada!',
    cancel: 'Cancelar',
    date_time: 'Fecha y Hora',
    now: 'Ahora',

    // Status labels
    normal: 'Normal',
    elevated: 'Elevada',
    high: 'Alta',
    crisis: 'Llamar al Médico',

    // Status descriptions
    normal_desc: 'Tu presión arterial está en un rango saludable.',
    elevated_desc: 'Tu presión arterial está ligeramente elevada.',
    high_desc: 'Tu presión arterial es alta. Monitorea de cerca.',
    crisis_desc: 'Tu presión arterial es muy alta. Contacta a tu médico inmediatamente.',

    // Validation
    enter_systolic: 'Por favor ingresa la presión sistólica',
    enter_diastolic: 'Por favor ingresa la presión diastólica',
    invalid_systolic: 'La sistólica debe estar entre 60 y 250',
    invalid_diastolic: 'La diastólica debe estar entre 40 y 150',
    invalid_pulse: 'El pulso debe estar entre 30 y 200',
  },

  // History & Charts
  history: {
    title: 'Historial',
    filter_day: 'Día',
    filter_week: 'Semana',
    filter_month: 'Mes',
    filter_two_weeks: '2 Semanas',
    filter_thirty_days: '30 Días',
    filter_custom: 'Personalizado',
    no_data: 'Sin lecturas en este período',
    average: 'Promedio',
    highest: 'Más alta',
    lowest: 'Más baja',
    readings_count: '{{count}} lecturas',
    systolic_label: 'Sistólica',
    diastolic_label: 'Diastólica',
    threshold_line: 'Límite normal',
    date_range: '{{start}} – {{end}}',
    export: 'Exportar',
  },

  // Medications
  medications: {
    title: 'Medicamentos',
    add: 'Agregar Medicamento',
    edit: 'Editar',
    delete: 'Eliminar',
    pause: 'Pausar',
    resume: 'Reanudar',
    name: 'Nombre del Medicamento',
    search_placeholder: 'Buscar medicamentos...',
    dosage: 'Dosis',
    frequency: 'Frecuencia',
    once_daily: 'Una vez al día',
    twice_daily: 'Dos veces al día',
    three_times_daily: 'Tres veces al día',
    four_times_daily: 'Cuatro veces al día',
    as_needed: 'Según sea necesario',
    doctor_notes: 'Notas del Médico',
    doctor_notes_placeholder: 'Instrucciones especiales de tu médico...',
    save: 'Guardar Medicamento',
    delete_confirm: '¿Estás seguro de que deseas eliminar este medicamento?',
    delete_yes: 'Sí, Eliminar',
    delete_no: 'Cancelar',
    paused_label: 'Pausado',
    active_label: 'Activo',
    no_medications: 'Sin medicamentos agregados',
    add_first: 'Agrega tu primer medicamento',
    reminder_set: 'Recordatorio establecido',
    category: 'Categoría',
  },

  // AI Recommendations
  ai: {
    title: 'Consejos de Salud',
    powered_by: 'Asistente de Salud IA',
    loading: 'Analizando tus lecturas...',
    no_data: 'Registra una lectura para recibir consejos personalizados.',
    disclaimer: 'Estas sugerencias son solo informativas. Consulta a tu médico antes de hacer cambios.',
    refresh: 'Nuevo Consejo',
    categories: {
      food: 'Nutrición',
      exercise: 'Actividad',
      hydration: 'Hidratación',
      sleep: 'Sueño',
      stress: 'Estrés',
      general: 'General',
      warning: 'Importante',
    },
  },

  // Notifications
  notifications: {
    bp_reminder_title: 'Es hora de revisar tu presión arterial',
    bp_reminder_body: 'Tómate un momento para registrar tu lectura.',
    medication_reminder_title: 'Recordatorio de medicamento',
    medication_reminder_body: 'Es hora de tomar tu {{medication}}.',
    elevated_warning_title: 'Presión arterial elevada detectada',
    elevated_warning_body: 'Tu última lectura fue {{systolic}}/{{diastolic}}. Monitorea de cerca.',
    high_warning_title: 'Alerta de presión arterial alta',
    high_warning_body: 'Tu lectura de {{systolic}}/{{diastolic}} es alta. Considera contactar a tu médico.',
    crisis_warning_title: 'Urgente: Presión arterial muy alta',
    crisis_warning_body: 'La lectura {{systolic}}/{{diastolic}} requiere atención médica inmediata.',
    missed_reading_title: '¿Olvidaste tu lectura?',
    missed_reading_body: 'No has registrado una lectura hoy. ¡Mantén el seguimiento!',
  },

  // Profile
  profile: {
    title: 'Perfil',
    name: 'Nombre',
    age: 'Edad',
    doctor_name: 'Nombre del Médico',
    doctor_phone: 'Teléfono del Médico',
    emergency_contact: 'Contacto de Emergencia',
    target_systolic: 'Sistólica Objetivo',
    target_diastolic: 'Diastólica Objetivo',
    save: 'Guardar Perfil',
    notifications: 'Notificaciones',
    reminders: 'Recordatorios',
    language: 'Idioma',
    data_export: 'Exportar Mis Datos',
    sign_out: 'Cerrar Sesión',
    sign_out_confirm: '¿Estás seguro de que deseas cerrar sesión?',
    data_retention: 'Los datos se eliminan automáticamente después de 2 años.',
    version: 'Versión',
  },

  // Auth
  auth: {
    sign_in: 'Iniciar Sesión',
    sign_up: 'Crear Cuenta',
    email: 'Correo Electrónico',
    password: 'Contraseña',
    confirm_password: 'Confirmar Contraseña',
    forgot_password: '¿Olvidaste tu contraseña?',
    reset_password: 'Restablecer Contraseña',
    no_account: '¿No tienes cuenta?',
    have_account: '¿Ya tienes cuenta?',
    create_account: 'Crear Cuenta',
    or: 'o',
    continue_with_google: 'Continuar con Google',
    terms: 'Al continuar, aceptas nuestros Términos de Servicio y Política de Privacidad.',
    error_invalid_email: 'Por favor ingresa un correo electrónico válido.',
    error_weak_password: 'La contraseña debe tener al menos 6 caracteres.',
    error_passwords_dont_match: 'Las contraseñas no coinciden.',
    error_generic: 'Algo salió mal. Por favor intenta de nuevo.',
  },

  // Common
  common: {
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    add: 'Agregar',
    back: 'Atrás',
    close: 'Cerrar',
    confirm: 'Confirmar',
    yes: 'Sí',
    no: 'No',
    ok: 'OK',
    loading: 'Cargando...',
    error: 'Algo salió mal',
    retry: 'Intentar de nuevo',
    no_internet: 'Sin conexión a internet',
    today: 'Hoy',
    yesterday: 'Ayer',
    mmhg: 'mmHg',
    bpm: 'lpm',
    morning: 'Mañana',
    afternoon: 'Tarde',
    evening: 'Noche',
  },
};
